import {
  Rocket,
  Search,
  Megaphone,
  Palette,
  TrendingUp,
  Target,
  BarChart3,
  Handshake,
  Lightbulb,
  ArrowLeft,
  ChevronDown,
  ChevronLeft,
  Menu,
  X,
  Sun,
  Moon,
  LayoutDashboard,
  CheckCircle2,
  Info,
  Send,
  Phone,
  Mail,
  MapPin,
  Camera,
  Briefcase,
  FileText,
  MessageSquare,
  Users,
  Settings,
  ExternalLink,
  LogOut,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

// Single icon registry backed by lucide-react (same icon set as CoachOps).
// Icons render at 1em so existing text-* size and color classes still apply.
const map: Record<string, LucideIcon> = {
  rocket: Rocket,
  search: Search,
  megaphone: Megaphone,
  palette: Palette,
  trending: TrendingUp,
  target: Target,
  bars: BarChart3,
  handshake: Handshake,
  bulb: Lightbulb,
  "arrow-left": ArrowLeft,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  menu: Menu,
  close: X,
  sun: Sun,
  moon: Moon,
  admin: LayoutDashboard,
  check: CheckCircle2,
  info: Info,
  send: Send,
  phone: Phone,
  mail: Mail,
  map: MapPin,
  instagram: Camera,
  linkedin: Briefcase,
  telegram: Send,
  pages: FileText,
  chat: MessageSquare,
  users: Users,
  settings: Settings,
  back: ExternalLink,
  signout: LogOut,
  sparkles: Sparkles,
};

export function Icon({ name, className = "" }: { name: string; className?: string }) {
  const Cmp = map[name] ?? Sparkles;
  return <Cmp className={`inline-block h-[1em] w-[1em] shrink-0 ${className}`} aria-hidden />;
}
